version: '3.8'

services:
  codekiosk:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
    restart: unless-stopped